services:
  - type: web
    name: ia-backend-prod
    env: node
    plan: starter
    branch: prod-backend-legacy
    buildCommand: |
      apt-get update
      apt-get install -y chromium || apt-get install -y chromium-browser
      apt-get install -y fonts-liberation fonts-noto-color-emoji
      which chromium || which chromium-browser || true
      chromium --version || chromium-browser --version || true
      npm ci --omit=dev
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://ia-frontend-prod.onrender.com
      - key: CORS_ORIGINS
        value: https://ia-frontend-prod.onrender.com
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"

  - type: web
    name: ia-backend-qa
    env: node
    plan: starter
    branch: qa-backend
    buildCommand: |
      apt-get update
      npm ci
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://ia-frontend-qa.onrender.com
      - key: CORS_ORIGINS
        value: https://ia-frontend-qa.onrender.com

  - type: web
    name: ia-backend-staging
    env: node
    plan: starter
    branch: staging-backend
    buildCommand: |
      apt-get update
      npm ci
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://ia-frontend-staging.onrender.com
      - key: CORS_ORIGINS
        value: https://ia-frontend-staging.onrender.com
