\set ON_ERROR_STOP on

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'postgres') then
    create role postgres nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin bypassrls;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'supabase_admin') then
    create role supabase_admin nologin;
  end if;
end
$$;

grant usage on schema public to anon, authenticated, service_role, postgres, supabase_admin;
grant create on schema public to postgres, supabase_admin;

alter default privileges for role postgres in schema public
  grant all privileges on tables to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant all privileges on sequences to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant execute on functions to public, anon, authenticated, service_role;

alter default privileges for role supabase_admin in schema public
  grant all privileges on tables to anon, authenticated, service_role;
alter default privileges for role supabase_admin in schema public
  grant all privileges on sequences to anon, authenticated, service_role;
alter default privileges for role supabase_admin in schema public
  grant execute on functions to public, anon, authenticated, service_role;

set role postgres;

create table public.accommodation_requests (id bigint generated by default as identity primary key, value text);
create table public.billing_events (id bigserial primary key, value text);
create table public.client_plan_settings (id bigint generated by default as identity primary key, value text);
create table public.contract_cancellation_runs (id bigint generated by default as identity primary key, value text);
create table public.contract_processing_runs (id bigint generated by default as identity primary key, value text);
create table public.conversations (id bigint generated by default as identity primary key, value text);
create table public.digest_logs (id bigint generated by default as identity primary key, value text);
create table public.feedback_issues_catalog (id bigint generated by default as identity primary key, value text);
create table public.feedback_submissions (id bigint generated by default as identity primary key, value text);
create table public.feedback_suggestions_catalog (id bigint generated by default as identity primary key, value text);
create table public.otp_tokens (id bigint generated by default as identity primary key, candidate_email text, role_id bigint, code text, created_at timestamptz default now());
create table public.pending_role_purchases (id bigint generated by default as identity primary key, value text);
create table public.request_rate_limits (
  route_name text not null,
  subject_key text not null,
  window_started_at timestamptz not null default now(),
  count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (route_name, subject_key)
);
create table public.role_interview_purchases (id bigint generated by default as identity primary key, value text);
create table public.rubric_change_requests (id bigint generated by default as identity primary key, value text);

create view public.v_latest_otp_per_email_role as
select distinct on (candidate_email, role_id)
  candidate_email, role_id, code, id, created_at
from public.otp_tokens
order by candidate_email, role_id, created_at desc;

create view public.role_candidate_counts as
select count(*)::bigint as candidate_count from public.otp_tokens;

create function public.check_and_increment_rate_limit(
  p_route_name text,
  p_subject_key text,
  p_window_ms integer,
  p_max_count integer
)
returns table (allowed boolean, count integer, remaining integer, retry_after_seconds integer)
language plpgsql
as $$
begin
  insert into public.request_rate_limits(route_name, subject_key, count)
  values (p_route_name, p_subject_key, 1)
  on conflict (route_name, subject_key)
  do update set count = request_rate_limits.count + 1, updated_at = now();
  return query
    select r.count <= p_max_count, r.count, greatest(0, p_max_count - r.count), 0
    from public.request_rate_limits r
    where r.route_name = p_route_name and r.subject_key = p_subject_key;
end
$$;

grant all privileges on all tables in schema public to anon, authenticated, service_role;
grant all privileges on all sequences in schema public to anon, authenticated, service_role;
grant execute on all functions in schema public to public, anon, authenticated, service_role;

reset role;
